### ISSUE TITLE
Action-bar: Missing borders when slotted in shellPanel

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-ui-kits#26]
CC related issue: https://github.com/Esri/calcite-components/issues/1926

- Add border start and end to action-bar when slotted in shell panel

**Comment by rmstinson** [comment]
Updated the light & dark start and end action Action Bars in Figma - had to style with drop shadow because Figma doesn't support different strokes for different sides. Used #D4D4D4 and #4A4A4A to match existing rule styles (light/ui-border-2 & dark/ui-border-2-dark.)

<img width="688" alt="Screen Shot 2021-09-02 at 5 39 37 PM" src="https://user-images.githubusercontent.com/12650705/131933333-44989605-7969-4989-83e7-5277a0f76d10.png">

Do we need to repeat the same styling for horizontal action bars as well?

<img width="886" alt="Screen Shot 2021-09-02 at 5 39 55 PM" src="https://user-images.githubusercontent.com/12650705/131933452-4a51fca4-ddfd-419b-830c-5e8bb0ed4051.png">

**Comment by macandcheese** [comment]
Thanks for adding this issue. My initial thought is that no, horizontal doesn’t need a border since the border in CC is applied when the action bar is slotted in a specific shell panel slot.

**Comment by julio8a** [comment]
Yeah, for now, let's tackle the vertical since that will sync with CC code. If the need arises for horizontal, we can do those in sync with code <-> Fig.

**Comment by julio8a** [comment]
is there an option to not have a border?

**Comment by rmstinson** [comment]
@julio8a So we can add another prop that toggles the shadow on/off in the Variant property pane, or we can just direct designers to remove the drop shadow that styles the action bar with the border.
![Screen Shot 2021-09-07 at 3 29 48 PM](https://user-images.githubusercontent.com/12650705/132418975-b4eec749-3c72-4fcd-bc8d-3cddd23265af.png)
___
![Screen Shot 2021-09-07 at 3 29 55 PM](https://user-images.githubusercontent.com/12650705/132418964-4c771203-abb2-4080-bf27-067a878d095b.png)

 Since the component doesn't have that property on the dev site, I think it  makes sense to just remove the drop shadow style when it's not needed on the designers' side, but I'm open to either!

**Comment by julio8a** [comment]
Yeah, I match what we have on the action-bar component. Also, if we were to advise designers on some usage (outside of the props), how would we do that? would there be a canvas with usage content? Seems like much, though.

**Comment by macandcheese** [comment]
I don't think the Figma file should contain usage documentation, since it will become another source of truth to update. Eventually, we will build out more design-focused content into the component pages on the docs site.

I know we don't really have a concept in Figma for "styled in this way as a result of being slotted"... but a prop to that end here could make sense (even though it may not fit in the paradigm of Figma props having a CC prop equivalent).

**Comment by rmstinson** [comment]
This was updated the other day to include a border toggle for start/end vertical action-bars, but since the horizontal action-bars don't have a border, it creates a little bit of a bug in the figma variant. 

Toggling the horizontal action bar's border from "off" to "on" will change it to a vertical action-bar start with the border turned on.

**Comment by julio8a** [comment]
Thanks for updating this. I think short-term this is fine. As we'll likely look at redesigning/restructuring the Figma components. 
Closing this one out for now. We can always open a new issue if needed.
